title: "Niklas Janßen's Portfolio"
description: "A showcase of my projects, including Game Dev, custom WeakAuras and Lua scripts."
author: "Niklas Janßen"
baseurl: "" 
url: "https://niklasjanssen.github.io" 
theme: jekyll-theme-minimal 
markdown: kramdown


plugins:
  - jekyll-feed
  - jekyll-seo-tag

